#!/bin/sh
#
# modprobe sound drivers
#

start() {
	modprobe snd_bcm2835
	modprobe snd_usb_audio
}
stop() {
	rmmod snd_usb_audio
	rmmod snd_bcm2835
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
